version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Configuración de Sphinx
sphinx:
  configuration: docs/conf.py

# Versión de Python y dependencias
python:
  version: 3.9
  install:
    - requirements: docs/requirements.txt
